"""Markdown report + deployment artifact generation."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import List

from .runner import Result
from .search import TuneLog
from .sysinfo import SystemInfo, summarize

DOCKERFILE_TMPL = """\
# Generated by armtune - optimal llama.cpp serving image for this Arm64 host
FROM --platform=linux/arm64 ubuntu:24.04 AS build
RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential cmake git ca-certificates && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/ggml-org/llama.cpp /src
# -mcpu=native picks up NEON/dotprod/i8mm/SVE on the build host
RUN cmake -S /src -B /build -DCMAKE_BUILD_TYPE=Release -DGGML_NATIVE=ON \\
    && cmake --build /build --target llama-server -j

FROM --platform=linux/arm64 ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libgomp1 curl && rm -rf /var/lib/apt/lists/*
COPY --from=build /build/bin/llama-server /usr/local/bin/llama-server
# Mount your {quant} model at /models/model.gguf
EXPOSE 8080
HEALTHCHECK CMD curl -f http://localhost:8080/health || exit 1
ENTRYPOINT ["llama-server", "-m", "/models/model.gguf", \\
  "-t", "{threads}", "-b", "{batch}", "--host", "0.0.0.0", "--port", "8080"{fa}]
"""

VALUES_TMPL = """\
# Generated by armtune - Helm values for arm64 llama.cpp serving
image:
  repository: your-registry/llama-server-arm64
  tag: latest
nodeSelector:
  kubernetes.io/arch: arm64
resources:
  requests:
    cpu: "{threads}"
    memory: {mem}Gi
  limits:
    cpu: "{threads}"
    memory: {mem_limit}Gi
server:
  threads: {threads}
  batch: {batch}
  flashAttention: {fa}
  model: /models/model.gguf   # {quant}
"""


def emit_deploy(best: Result, model_gb: float, outdir: Path) -> List[Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    cfg = best.config
    fa = ', "-fa", "1"' if cfg.flash_attn else ""
    docker = DOCKERFILE_TMPL.format(quant=cfg.quant, threads=cfg.threads, batch=cfg.batch, fa=fa)
    mem = max(2, int(model_gb + 1.5))
    values = VALUES_TMPL.format(
        threads=cfg.threads, batch=cfg.batch, quant=cfg.quant,
        fa=str(cfg.flash_attn).lower(), mem=mem, mem_limit=mem + 2,
    )
    p1 = outdir / "Dockerfile"
    p2 = outdir / "values.yaml"
    p1.write_text(docker)
    p2.write_text(values)
    return [p1, p2]


def render_report(si: SystemInfo, results: List[Result], log: TuneLog,
                  model_name: str, mock: bool) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    best = results[0]
    baseline = min(results, key=lambda r: r.score())
    speedup = best.score() / baseline.score() if baseline.score() else 0
    lines = [
        f"# armtune report - {model_name}",
        f"_Generated {now}_",
        "",
        "## Host",
        "```",
        summarize(si),
        "```",
        "",
    ]
    if mock:
        lines += ["> **Mock mode** - numbers come from armtune's calibrated analytical "
                  "model (non-Arm dev host). Run on Arm64 for real measurements.", ""]
    lines += [
        "## Winner",
        "",
        f"| | |",
        f"|---|---|",
        f"| Config | **{best.config.label()}** |",
        f"| Generation | **{best.tg_tps} tok/s** |",
        f"| Prompt processing | **{best.pp_tps} tok/s** |",
        f"| Speedup vs worst evaluated | **{speedup:.1f}x** |",
        "",
        "## Leaderboard (final round)",
        "",
        "| # | Config | Gen tok/s | Prompt tok/s | Score |",
        "|---|--------|-----------|--------------|-------|",
    ]
    for i, r in enumerate(results[:10], 1):
        lines.append(f"| {i} | {r.config.label()} | {r.tg_tps} | {r.pp_tps} | {r.score():.1f} |")
    lines += ["", "## Agent decisions", ""]
    for d in log.decisions:
        lines.append(f"- {d}")
    lines += [
        "",
        "## Ship it",
        "",
        "Deployment artifacts generated in `deploy/`:",
        "- `Dockerfile` - arm64 llama.cpp server image built with `-mcpu=native`",
        "- `values.yaml` - Helm values pinned to the winning config, `arm64` nodeSelector",
        "",
    ]
    return "\n".join(lines)


def save_json(si: SystemInfo, results: List[Result], log: TuneLog, path: Path) -> None:
    path.write_text(json.dumps({
        "system": si.to_dict(),
        "results": [r.to_dict() for r in results],
        "rounds": log.rounds,
        "decisions": log.decisions,
    }, indent=2))
